### ISSUE TITLE
Erro Usuario Hugo

### ISSUE THREAD

**Issue by hebercosta** [diego-goulart/skill#2]
Diego no cadastro do Hugo está com erro, acho que o mesmo não está com perfil de Supervisor e quando eu tentei cadastrar ele aparece o erro em anexo
![erro 2](https://cloud.githubusercontent.com/assets/25610279/22718410/693d70a4-ed87-11e6-9a42-59f5d2c47581.PNG)

**Comment by diego-goulart** [comment]
O usuário só pode ser cadastrado uma única vez.
Não são permitidos usuários com o mesmo número de matrícula.


Conforme a imagem mostrada abaixo, verifique as permissões do hugo, pois ele não está cadastrado como supervisor, e também não há equipes ligadas a ele.

![image](https://cloud.githubusercontent.com/assets/17575204/22737182/108d5714-ede9-11e6-8105-a72bec1930b0.png)
