### ISSUE TITLE
Erro ao salvar monitoria

### ISSUE THREAD

**Issue by hebercosta** [diego-goulart/skill#6]
Diego quando a Lider Laureana foi cadastrar a monitoria ocorreu erro abaixo
![erro](https://cloud.githubusercontent.com/assets/25610279/22797739/98b9d9fc-eee6-11e6-823d-8a54b88addf6.PNG)

**Comment by djgoulart** [comment]
@hebercosta  O líder precisa digitar a data no formato: DD/MM/YYY, e a hora no formato HH:MM
